### ISSUE TITLE
Multiple anonymous defines during Bundling

### ISSUE THREAD

**Issue by brettveenstra** [aurelia/loader-default#31]
Getting an `Error: Multiple anonymous defines.` when attempting to run `gulp bundle` on a fresh folder (in a CI setting).  Our dev machines work just fine and this CI environment is different only in that it clears the working folder on each build and calls, `npm install` and `jspm install` prior to `gulp bundle` operation.  The CI machine only started getting these errors Feb 25, 2016.  Again, this works on multiple other boxes (see also https://github.com/aurelia/skeleton-navigation/issues/310)

The stack looks like this (projectpath substituted for actual location):

	Error on instantiate for npm:aurelia-loader-default@1.0.0-beta.1.1.2/aurelia-loader-default.js at file:///{projectpath}/jspm_packages/npm/aurelia-load
	er-default@1.0.0-beta.1.1.2/aurelia-loader-default.js
			Loading npm:aurelia-loader-default@1.0.0-beta.1.1.2.js
			Error: Multiple anonymous defines.
		at ParseTreeTransformer.AMDDependenciesTransformer.transformCallExpression ({projectpath}\node_modules\systemjs-builder\compilers\amd.js:98:13)
		at CallExpression.$__super.transform ({projectpath}\node_modules\traceur\bin\traceur.js:6649:28)
		at ParseTreeTransformer.transformAny ({projectpath}\node_modules\traceur\bin\traceur.js:9193:44)
		at ParseTreeTransformer.transformExpressionStatement ({projectpath}\node_modules\traceur\bin\traceur.js:9504:31)
		at ExpressionStatement.$__super.transform ({projectpath}\node_modules\traceur\bin\traceur.js:7120:28)
		at ParseTreeTransformer.transformAny ({projectpath}\node_modules\traceur\bin\traceur.js:9193:44)
		at ParseTreeTransformer.transformList ({projectpath}\node_modules\traceur\bin\traceur.js:9200:34)
		at ParseTreeTransformer.transformFunctionBody ({projectpath}\node_modules\traceur\bin\traceur.js:9574:31)
		at FunctionBody.$__super.transform ({projectpath}\node_modules\traceur\bin\traceur.js:7293:28)
		at ParseTreeTransformer.transformAny ({projectpath}\node_modules\traceur\bin\traceur.js:9193:44)
		at ParseTreeTransformer.transformFunctionExpression ({projectpath}\node_modules\traceur\bin\traceur.js:9596:25)
		at ParseTreeTransformer.AMDDependenciesTransformer.transformFunctionExpression ({projectpath}\node_modules\systemjs-builder\compilers\amd.js:61:69)
		at FunctionExpression.$__super.transform ({projectpath}\node_modules\traceur\bin\traceur.js:7339:28)
		at ParseTreeTransformer.transformAny ({projectpath}\node_modules\traceur\bin\traceur.js:9193:44)
		at ParseTreeTransformer.transformBinaryExpression ({projectpath}\node_modules\traceur\bin\traceur.js:9299:26)
		at BinaryExpression.$__super.transform ({projectpath}\node_modules\traceur\bin\traceur.js:6557:28)
		at ParseTreeTransformer.transformAny ({projectpath}\node_modules\traceur\bin\traceur.js:9193:44)
		at ParseTreeTransformer.transformExpressionStatement ({projectpath}\node_modules\traceur\bin\traceur.js:9504:31)
		at ExpressionStatement.$__super.transform ({projectpath}\node_modules\traceur\bin\traceur.js:7120:28)
		at ParseTreeTransformer.transformAny ({projectpath}\node_modules\traceur\bin\traceur.js:9193:44)
		at ParseTreeTransformer.transformList ({projectpath}\node_modules\traceur\bin\traceur.js:9200:34)
		at ParseTreeTransformer.transformBlock ({projectpath}\node_modules\traceur\bin\traceur.js:9317:31)
		at Block.$__super.transform ({projectpath}\node_modules\traceur\bin\traceur.js:6612:28)

**Comment by StrahilKazlachev** [comment]
I think this was resolved, check aurelia/bundler#88

**Comment by EisenbergEffect** [comment]
Please to run `jspm update`. That bug was fixed and released.
